### ISSUE TITLE
Allow a way to override what funnel_cake_index branch is used.

### ISSUE THREAD

**Issue by dkinzer** [tulibraries/funcake_dags#19]
Right now "master" branch is used by default but if we we may want to override what gets used int eh dev environment for testing purposes.

One idea is to check of FUNNEL_CAKE_INDEX_DEV_BRANCH ariflow variable and if that exists to use what's set there otherwise fall back to using master.

**Comment by cmharlow** [comment]
Working branch on this from a while back here: https://github.com/tulibraries/funcake_dags/tree/add-indexer-branch-variable
